name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --workspace --verbose
    - name: Run tests
      run: cargo test --workspace --verbose
    - name: Run Clippy
      run: cargo clippy --workspace --verbose
    - name: Run Rustfmt
      run: cargo fmt -- --check